### ISSUE TITLE
Cohorts Validation has an illegal LocalJumpError when running with coverage

### ISSUE THREAD

**Issue by blackrat** [DFE-Digital/early-careers-framework#336]
### What did you do? (steps to reproduce)

Ran the rspec test suite with coverage

### What happened? (actual results)
```
The test failed with:
Admin::Suppliers::DeliveryPartners POST /admin/suppliers/new/delivery-partner/choose-cohorts displays an error when no cohorts are selected for a lead provider
     Failure/Error: break

     LocalJumpError:
       break from proc-closure
     # ./app/forms/delivery_partner_form.rb:86:in 'block in cohorts_validation'
```

**Comment by ethanmills** [comment]
I suspect this is an issue with your setup. Nobody else has encountered this as far as I'm aware, and it hasn't come up in CI

**Comment by blackrat** [comment]
It's a definite issue since you shouldn't break inside a block. changing it to a return will fix it, since it's just wants to record an error and return.

**Comment by kicferk1** [comment]
```
  def cohorts_validation
    # Ensure all selected lead providers have at least one selected cohort
    # This is indicated by the presence of a provider relationship for that lead provider
    lead_provider_ids&.filter(&:present?)&.each do |lead_provider_id|
      unless chosen_provider_relationships.pluck(:lead_provider_id).include?(lead_provider_id)
        errors.add(:provider_relationship_hashes, :blank, message: "Choose at least one cohort for every lead provider")
        break
      end
    end
  end
```
is the code it probably talks about. Feel free to refactor it not to use `break`, or to use it better. Although truth be told, the code looks reasonable to me - if we ever find a cohort that's missing, we stop looking. I think `break` refers to the `each do`, is there some subtle ruby magic that I am missing? Should we be using `return` instead? :P

**Comment by tonyheadford** [comment]
Not sure that `return` will help, I think it's still possible to get that error if you `return` from a proc

**Comment by blackrat** [comment]
Both break and return have different issues when used inside procs or lambdas. Best thing is to avoid them. Simplest fix is to drop the break line and switch the .each to .any?

I've done a quick test and refactor. All tests are passing still. Also double verified that what I thought about errors.add (and any?) were true.
