### ISSUE TITLE
Tests with coverage fail to run until Gems are updated

### ISSUE THREAD

**Issue by blackrat** [DFE-Digital/early-careers-framework#337]
Ran rspec with coverage on the specs which failed to run.
Ran `bundle update` to allow it to update all out-of-date gems and ran it again which succeeds (generated an error in one of the tests which has been raised separately as an issue).

One (or more) of the gems is causing this. At first I thought it was the simplecov gem itself, but updating that on its own didn't fix it, which is why I tried just doing them all. Needs investigation to find out which is stopping it, or to update all of them to stop it.

**Comment by ethanmills** [comment]
Works fine for me as-is on latest develop

**Comment by blackrat** [comment]
Seems ok with the latest develop branch.
