### ISSUE TITLE
20210323180540_change_item_id_type_to_uuid.rb changes column type and throws any data away

### ISSUE THREAD

**Issue by blackrat** [DFE-Digital/early-careers-framework#339]
This is a migration that converts the papertrail item_id from bigint to uuid by dropping the column and recreating it with random data. This will break the referential integrity of the papertrail items, rendering them useless up to the point of the migration.

The original foreign key data was lost by this migration. In addition, you can't roll back, since that will fail.

**Comment by ethanmills** [comment]
> The original foreign key data was lost by this migration
There wasn't any original foreign key data to lose. Firstly, this was before we deployed to production. Secondly, since UUIDs were being cast to ints, we only had the characters of the ID before the first letter. 

Is there a change you'd like here, or can we close this?

**Comment by blackrat** [comment]
Close it.
