### ISSUE TITLE
Rename LeadProvider to EcfLeadProvider

### ISSUE THREAD

**Issue by timabell** [DFE-Digital/early-careers-framework#698]
The current name is confusing. See #656 for more context.

After a bit of confusion it transpired that `LeadProvider` actually meant `EcfLeadProvider` (ECF = Early Careers Framework), and that "ECF" was *implicit* because that's in the repo name `early-careers-framework`.... the repo has since expanded in scope to also cover NPQ (National Professional Qualifications), (although the repo also retains the original name).

#656 bumped [Ecf]LeadProvider down in the hierarchy and added a top-level `CpdLeadProvider` (CPD = Continuing Professional Development), and an additional `NpqLeadProvider`, however renaming this entity requires more work so has been left as this cleanup task (tech debt).

**Comment by BroiSatse** [comment]
I wonder, we have quite a few ECF models now - should we start thinking about a ECF namespace?

**Comment by blackrat** [comment]
> I wonder, we have quite a few ECF models now - should we start thinking about a ECF namespace?

I think having `ECF` and `NPQ` namespaces make a lot of sense.
