### ISSUE TITLE
`lead_providers.cpd_lead_provider_id` should not be nullable

### ISSUE THREAD

**Issue by timabell** [DFE-Digital/early-careers-framework#757]
`lead_providers.cpd_lead_provider_id` should be `NOT NULL`

https://github.com/DFE-Digital/early-careers-framework/blob/816909b2d2b15c3c73c816cd1924a19302864fec/db/schema.rb#L290

The `lead_provider` (aka `ecf_lead_provider` #698) must always have a parent `cpd_lead_provider` record to be valid. The schema should enforce this.

**Comment by asmega** [comment]
this can be done now. it wasn't possible when this was added as the creating a column with not null is not possible if there is no default.
